cmake_minimum_required(VERSION 3.8)
project(sp_nav_tools)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_AUTOMOC ON)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(action_msgs REQUIRED)
find_package(robot_msg REQUIRED)
find_package(visualization_msgs REQUIRED)
find_package(rviz_common REQUIRED)
find_package(pluginlib REQUIRED)
find_package(Qt5 REQUIRED COMPONENTS Widgets)
add_library(fixed_goal_panel SHARED src/fixed_goal_panel.cpp)
ament_target_dependencies(fixed_goal_panel rclcpp geometry_msgs nav_msgs action_msgs rviz_common pluginlib)
target_link_libraries(fixed_goal_panel Qt5::Widgets)
add_executable(robot_marker_publisher src/robot_marker_publisher.cpp)
ament_target_dependencies(robot_marker_publisher rclcpp robot_msg visualization_msgs)
pluginlib_export_plugin_description_file(rviz_common plugin_description.xml)
install(TARGETS fixed_goal_panel robot_marker_publisher
  LIBRARY DESTINATION lib
  RUNTIME DESTINATION lib/${PROJECT_NAME})
ament_package()
